name: Ubuntu

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  BUILD_TYPE: Release
  INSTALL_LOCATION: .local

jobs:
  build:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v2

      - name: cache dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: ${{ github.workspace }}/${{ env.INSTALL_LOCATION }}
          key: ${{ runner.os }}-dependencies

      - name: install thirdparty
        if: ${{ steps.cache.output.cache-hit != 'true' }}
        run: |
          cmake --build build --config $BUILD_TYPE --target=fmt -j4
          cmake --build build --config $BUILD_TYPE --target=gtest -j4
          cmake --build build --config $BUILD_TYPE --target=gtest_main -j4

      - name: build
        run: cmake --build build --config $BUILD_TYPE -j4

      - name: run tests
        run: |
          cd build
          ctest -C $BUILD_TYPE -VV

      - name: Code coverage using Codecov
        run: bash <(curl -s https://codecov.io/bash)

      - name: install project
        run: cmake --build build --target install --config Release
