name: Windows

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

env:
  BUILD_TYPE: Release
  INSTALL_LOCATION: ".local"

jobs:
  build:
    runs-on: windows-latest
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - uses: actions/checkout@v2

      - name: cache dependencies
        uses: actions/cache@v2
        id: cache
        with:
          path: ${{env.INSTALL_LOCATION}}
          key: ${{runner.os}}-dependencies

      - name: install thirdparty
        if: ${{ steps.cache.output.cache-hit != 'true' }}
        run: |
          ls
          mkdir
          cmake --build build --config $BUILD_TYPE --target=fmt -j4
          cmake --build build --config $BUILD_TYPE --target=gtest -j4
          cmake --build build --config $BUILD_TYPE --target=gtest_main -j4

      - name: build
        run: cmake --build build --config "$env:BUILD_TYPE" -j4

      - name: run tests
        run: |
          cd build
          ctest -C "$env:BUILD_TYPE" -VV

      - name: install project
        run: cmake --build build --target install --config Release
